-- create table supplier(
-- 	id int NOT NULL generated by default as identity,
-- 	nama varchar(50),
-- 	alamat varchar(100),
-- 	no_hp varchar(15),
-- 	constraint supplier_nama unique(nama),
-- 	constraint supplier_pkey primary key(id)
-- );


-- create table barang(
-- 	id int NOT NULL generated by default as identity,
-- 	nama varchar(100),
-- 	satuan varchar(100),
-- 	stok int,
-- 	harga int,
-- 	supplier_id int,
-- 	constraint barang_pkey primary key(id),
-- 	constraint supplier_id_pkey foreign key(supplier_id) references supplier(id)
-- );

-- create table pembeli(
-- 	id int NOT NULL generated by default as identity,
-- 	nama varchar(50),
-- 	alamat varchar(100),
-- 	jenis_kelamin varchar(1),
-- 	no_hp varchar(15),
-- 	constraint pembeli_nama unique(nama),
-- 	constraint pembeli_pkey primary key(id)
-- );

-- create table pesanan(
-- 	id int NOT NULL generated by default as identity,
-- 	barang_id int,
-- 	pembeli_id int,
-- 	constraint pesanan_pkey primary key(id),
-- 	constraint barang_id_pkey foreign key(barang_id) references barang(id),
-- 	constraint pembeli_id_pkey foreign key(pembeli_id) references pembeli(id)
-- );

-- insert into supplier(
-- values
-- (101, 'berkah maju', 'jakarta selatan', '08124365445'),
-- (102, 'maju mulus', 'jakarta barat', '0814345665445'),
-- (103, 'berkah sukses', 'jakarta barat', '08124365114354'),
-- (104, 'sukses bersama', 'jakarta timur', '0812376867')
-- )

-- insert into barang(
-- values
-- (9001, 'gas 3 kg ', 'kg', 30, 18000 , 103),
-- (9002, 'beras 5 kg', 'kg', 100, 85000, 101),
-- (9003, 'minyak bimoli 1 lt', 'lt', 200, 12000, 102),
-- (9004, 'santan kara 2 gr', 'gr', 400, 2000, 104),
-- (9005, 'kecap bango 1 lt', 'lt', 100, 25000, 102)
-- )

-- insert into pembeli(
-- values
-- (2201, 'Anton', 'jakarta selatan', 'L', '08124365445'),
-- (2202, 'Rini', 'jakarta barat', 'P',  '0814345665445'),
-- (2203, 'Beni', 'jakarta barat',  'L', '08124365114354'),
-- (2204, 'Dodo', 'jakarta timur', 'L',  '0812376867'),
-- (2205, 'Feri', 'jakarta selatan', 'L',  '0812375436'),
-- (2206, 'Mira', 'jakarta timur', 'P',  '0812376111')
-- )

-- insert into pesanan(
-- values
-- (71001, 9005, 2202),
-- (71002, 9001, 2206),
-- (71003, 9004, 2204),
-- (71004, 9004, 2204),
-- (71005, 9002, 2201),
-- (71006, 9003, 2203),
-- (71007, 9005, 2205),
-- (71008, 9001, 2202),
-- (71009, 9003, 2202)
-- )

-- update barang
-- set stok = 120
-- where nama = 'gas 3kg'

-- delete from pesanan
-- where id = 71009

-- select distinct barang_id from pesanan

-- create table barang_cp(
-- 	id int NOT NULL generated by default as identity,
-- 	nama varchar(100),
-- 	satuan varchar(100),
-- 	stok int,
-- 	harga int,
-- 	supplier_id int,
-- 	constraint barangcp_pkey primary key(id),
-- 	constraint supplier_id_pkey foreign key(supplier_id) references supplier(id)
-- );

-- insert into barang_cp(
-- values
-- (9101, 'royco 5gr', 'gr', 100, 2000 , 103),
-- (9102, 'terasi udang 5gr', 'gr', 80, 5000, 101),
-- (9103, 'minyak kelapa 5lt', 'lt', 18, 22000, 102),
-- (9104, 'gulaku 5 gr', 'gr', 100, 1500, 104),
-- (9105, 'saori 1 lt', 'lt', 60, 17000, 102)
-- )

-- select * from barang_cp
